default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  timeout: 5000
  username: root
  password: root

development:
  <<: *default
  database: elevo_demo

test:
  <<: *default
  database: elevo_demo_test

production:
  <<: *default
  database: elevo_demo_prod
